Docs/pt 5083 account validator
placetopay-org/placetopay-docs pull request #107
Opened 2024-09-17 13:12 UTC by ValeriaHerreraP

Se realiza migración de la documentación Account Validator API.

2024-09-17 13:12 UTC, ValeriaHerreraP commented
Se realiza migración de la documentación Account Validator API.

2024-09-18 16:15 UTC, anagranada1 commented
Hola

2024-09-18 20:11 UTC, meiyerDev requested changes
Todos las páginas deben poseer traducción al inglés o en su defecto, ser duplicados bajo el scope `pages/en` para que asi la la pagina exista en este idioma.

De no traducirse se requiere que al inciio de cada archivo bajo el scope `en` lleve el este componente declarado:

`<MissingTranslationBanner />`

2024-09-18 20:11 UTC, meiyerDev commented on src/assets/apis/account-validator/es.yaml
> +openapi: 3.1.0
Debemos crear la versión en inglés. En caso de no hacerse en la primera etapa, se debe duplicar el archivo con nombre `en.yaml`

2024-09-18 20:11 UTC, meiyerDev commented on src/constants/navigations.js
> +    [LANGUAGES_CODES.ES]: [
Agregar traducción de las rutas, al ser solo pocas lineas, si se requiere traducción de las mismas

2024-09-18 20:11 UTC, meiyerDev commented on src/components/SelectMenu.jsx
> +    {
Agregar traducción al inglés

2024-09-18 20:11 UTC, meiyerDev commented on src/pages/index.mdx
> +
agregar traducción en la ruta `pages/en/index.mdx`

2024-09-18 22:06 UTC, meiyerDev approved these changes

2024-09-18 22:06 UTC, merged