Add balance service documentation
placetopay-org/placetopay-docs pull request #137
Opened 2024-11-01 15:10 UTC by lcath

* Se agrega documentación de la bandera 'requiresBalance' en information
* Se agrega documentación de servicio de consulta de balance para Transerver

2024-11-01 15:41 UTC, vale0722 approved these changes

2024-11-01 15:46 UTC, vale0722 approved these changes

2024-11-05 18:56 UTC, andrextor requested changes

2024-11-05 18:56 UTC, andrextor commented on src/pages/gateway/api/reference/information.mdx
> +        Este servicio permite consultar la información de balance. Se debe consumir si el método de pago lo requiere (Cuando 'requireBalance' es 'true' en la respuesta obtenida del servicio de inform
¿Por qué es diferente la traducción en inglés? Es cierto que es posible cambiar la forma de comunicar el mensaje según el idioma para dar mejor contexto, pero en esta ocasión veo diferencias en la información dada:

This service should be consumed if the payment method requires it (requireBalance flag set to true in the information service response).

2024-11-05 19:29 UTC, andrextor approved these changes

2024-11-05 19:30 UTC, merged