Feature/PT-4394 updating MPI Contracts for 3DS Version 2x
placetopay-org/placetopay-docs pull request #145
Opened 2024-11-14 17:54 UTC by miguelCastanedaV

Se realiza modificación en documentación de endpoints MPI lookup y MPI Query para agregar peticiones de envío  y respuestas versionadas.

[Tarea PT-4394](https://app.clickup.com/t/31051369/PT-4394)

2024-11-22 21:57 UTC, vale0722 approved these changes

2024-12-20 20:27 UTC, vale0722 approved these changes

2024-12-24 13:48 UTC, eduarguz requested changes

2024-12-24 13:48 UTC, eduarguz commented on src/assets/apis/gateway/es.yaml
> +                  title: "Instrumento (Propiedad Obsoleta)"
El instrument a pesar de que ahora es obsoleto, sí se envía en producción, entonces es mejor mantener la definición completa

2024-12-24 13:48 UTC, eduarguz commented on src/assets/apis/gateway/es.yaml
> +        - "expiration"
Hay casos en los que expiration no es requerido

2024-12-24 13:48 UTC, eduarguz commented on src/assets/apis/gateway/es.yaml
> +    ThreeDSQueryV2:
Este no veo que se use

2024-12-24 14:06 UTC, miguelCastanedaV commented on src/assets/apis/gateway/es.yaml
> +                  title: "Instrumento (Propiedad Obsoleta)"
Se realiza modificación acorde a retroalimentación

2024-12-24 14:06 UTC, miguelCastanedaV commented on src/assets/apis/gateway/es.yaml
> +        - "expiration"
Se realiza modificación acorde a retroalimentación

2024-12-24 14:07 UTC, miguelCastanedaV commented on src/assets/apis/gateway/es.yaml
> +    ThreeDSQueryV2:
Se elimina esquema sin uso

2024-12-24 14:18 UTC, eduarguz approved these changes

2024-12-24 14:24 UTC, merged