feat: add docs about additional data in gateway
placetopay-org/placetopay-docs pull request #70
Opened 2024-07-22 18:10 UTC by mascam97

2024-07-23 13:11 UTC, andrextor commented
agregar también en :

-  [Pagos.reembolsos.respuesta.payment](https://github.com/mascam97/placetopay-docs.git)
- [Pagos.AccionesDeTransacción.response](https://github.com/mascam97/placetopay-docs.git)
- [Token.CobroUsandoToken.respuesta](https://github.com/mascam97/placetopay-docs.git)

2024-07-23 13:13 UTC, andrextor requested changes

2024-07-23 13:13 UTC, andrextor commented on src/pages/en/gateway/additional-data.mdx
> +Below are some examples of the additional data that may be received when processing a transaction:
La descripción ya esta implícita en el mismo título.

2024-07-25 14:50 UTC, vale0722 commented on src/components/AdditionalDataExamples.jsx
> +        es: "Línea.",
Posición en el archivo de cierre (Línea)

2024-07-25 20:42 UTC, andrextor approved these changes

2024-07-25 20:43 UTC, merged